server.port=5432
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/sololearn_uz_db
spring.datasource.username=postgres
spring.datasource.password=1122
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=never

#jwt.secret = rWHdVPWbqsBDDcQs0PdArBwcZLkH5yykj3l4I
#jwt.expiry.date = 86400000
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
server.tomcat.threads.max=200
